### ISSUE TITLE
Any possibility to use LiClipseText in a standalone dialog?

### ISSUE THREAD

**Issue by brsanthu** [fabioz/LiClipseText#11]
Title says it all.

It is great that LiClipseText supports so many languages. Is it possible use that editor in a standalone manner inside a dialog for example?

**Comment by fabioz** [comment]
I must say that I've never tried that, so, I don't really know (if there are shortcomings they'd be related to inheriting org.eclipse.ui.editors.text.TextEditor).

If it doesn't work out of the box, it'd certainly be possible to structure the code to support that (or at least make most features available to be used in a StyledText inside a dialog).
