### ISSUE TITLE
Question: how to combine Yaml + Jinja2 languages?

### ISSUE THREAD

**Issue by max-arnold** [fabioz/LiClipseText#13]
Both SaltStack and Ansible use Yaml + Jinja2 to describe configurations. Is it possible to combine these editors in LiClipseText for specific file extension?

**Comment by fabioz** [comment]
Hi Max,

In theory yes, that should be possible... it should be mostly a matter of combining the definition of both as needed (although that may require some fiddling around with the related files).

As a reference, the jinja2 and yaml definitions used are:

https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/languages/jinja2.liclipse
https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/languages/yaml.liclipse

There are some instructions at http://www.liclipse.com/text/supported_languages.html on how to create your own `.liclipse` file.

It should also be possible to `embed` one inside the other. For instance, `mako` embeds `python` (see: https://github.com/fabioz/LiClipseText/blob/fa7860088569a8e024fd42ba7a8ce053ac7ac1c9/plugins/org.brainwy.liclipsetext.editor/languages/mako.liclipse -- in particular, search for `SwitchLanguageRule` there).

**Comment by max-arnold** [comment]
Thank you Fabio!
