### ISSUE TITLE
Critical! p2 update not available now (today and after 1 of May) due Bintray sunset

### ISSUE THREAD

**Issue by marmyshev** [fabioz/LiClipseText#19]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please publish p2 on new server!

**Comment by fabioz** [comment]
Thanks for the heads up. Will do.

**Comment by fabioz** [comment]
This is now done (it's now hosted directly at GitHub releases).
